server:
  port: 8053

spring:
  application:
    name: stock-server

eureka:
  client:
    service-url:
      defaultZone: http://doubleDimple:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true