server:
  port: 8761

spring:
  application:
    name: eurekaServer

  #权限认证
  security:
    basic:
      enabled: true
    user:
      name: doubleDimple
      password: 123456
  boot:
    admin:
      context-path: /admin

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://doubleDimple:123456@localhost:8761/eureka/
  server:
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS